version: '3.8'
services:
  webserver:
    build:
      context: ./project
      dockerfile: ../Dockerfile
      target: $DOCKER_BUILD_ENV
    ports:
      - 3000:3000
      - 3001:3001
      - 7000:7000